using System.ComponentModel;
using System.Collections.Generic;
using CodeSmith.Engine;
using System.Text;
using System.Text.RegularExpressions;



public class CommonTemplate : CodeTemplate
{
	
private string _entityName;
  private bool  _stringEnums;
	
	[Category("Context")]
	[Optional]
	[Description("If this template is being called directly, then specify the element name to target.")]
	
	public string EntityName
	{ 
		get {return _entityName;}
		set {_entityName = value;}
	}

	[Category("Context")]
	[Optional]
	[DefaultValue( false)]
	[Description("specified if enums stored as string or integers .")]
	
	public bool StringEnums
	{ 
		get {return _stringEnums;}
		set {_stringEnums = value;}
	}


	
	

public void bulidMethodComment(string Type,  string name )
{
Response.IndentLevel = 1;	
Response.WriteLine("/*");
Response.WriteLine("//Method " +name);


Response.WriteLine("//return "+Type);
Response.WriteLine("*/");
Response.IndentLevel = 0;
	
	
}

public void bulidGenerateHeader()
{
	Response.WriteLine("//------------------------------------------------------------------------------");
	Response.WriteLine("// <autogenerated>");
	Response.WriteLine("//     This code was generated by a CodeSmith Template.");
	Response.WriteLine("//");
	Response.WriteLine("//     DO NOT MODIFY contents of this file. Changes to this");
	Response.WriteLine("//     file will be lost if the code is regenerated.");
	Response.WriteLine("// </autogenerated>");
	Response.WriteLine("//------------------------------------------------------------------------------");
}


public void bulidUpdatableGenerateHeader()
{
	Response.WriteLine("//------------------------------------------------------------------------------");
	Response.WriteLine("// <autogenerated>");
	Response.WriteLine("//    This code was generated by a CodeSmith Template.");
	Response.WriteLine("//");
	Response.WriteLine("//    This is for customizing generated code");
	Response.WriteLine("//    All changes made in this file will be preserved.");
	Response.WriteLine("// </autogenerated>");
	Response.WriteLine("//------------------------------------------------------------------------------");
}



}



