//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;

namespace SS.DL.AzureTableStorage
{
    public class  ErrorMappings : TableServiceEntity
    {
        
		public  ErrorMappings()
        {

        }
		
	 	
        
        
        /// <summary>
        /// Gets or sets the ErrorMessage Property value.
        /// </summary>
        public  string   	ErrorMessage              {get; set;}
        
        /// <summary>
        /// Gets or sets the UserError Property value.
        /// </summary>
        public  bool     	UserError                 {get; set;}
        
	
	


    }    

 }
