//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;

namespace SS.DL.AzureTableStorage
{
    public class  Questions : TableServiceEntity
    {
        
		public  Questions()
        {

        }
		
	 	
        
        
        /// <summary>
        /// Gets or sets the SectionName Property value.
        /// </summary>
        public  string   	SectionName               {get; set;}
        
        /// <summary>
        /// Gets or sets the Options Property value.
        /// </summary>
        public  string   	Options                   {get; set;}
        
        /// <summary>
        /// Gets or sets the Name Property value.
        /// </summary>
        public  string   	Name                      {get; set;}
        
        /// <summary>
        /// Gets or sets the InputType Property value.
        /// </summary>
        public  int      	InputType                 {get; set;}
        
        /// <summary>
        /// Gets or sets the IsAnswerReq Property value.
        /// </summary>
        public  bool     	IsAnswerReq               {get; set;}
        
        /// <summary>
        /// Gets or sets the Answer Property value.
        /// </summary>
        public  int      	Answer                    {get; set;}
        
        /// <summary>
        /// Gets or sets the IsPositive Property value.
        /// </summary>
        public  bool     	IsPositive                {get; set;}
        
	
	


    }    

 }
