//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization.Json;
using SS.Framework.Common;

namespace SS.DL.AzureTableStorage
{
    public class  Questionaire 
	
    {
    
		 Questionaires _Questionaires;
		
		public  Questionaire( Questionaires Par)
        {
			_Questionaires = Par;
        }
		public  Questionaire( )
        {
			_Questionaires = new Questionaires ();
        }
		
		public string RowKey  
		{
			get 
			{
				return _Questionaires.RowKey;
			}
		}
        /// <summary>
        /// Gets or sets the QuestionaireId Property value.
        /// </summary>
        public  string   	QuestionaireId            { get { return _Questionaires.PartitionKey; } set { _Questionaires.PartitionKey = value; } }
        
        /// <summary>
        /// Gets or sets the QuestionId Property value.
        /// </summary>
        public  string   	QuestionId                { get { return _Questionaires.RowKey; } set { _Questionaires.RowKey = value; } }
        
        /// <summary>
        /// Gets or sets the SectionName Property value.
        /// </summary>
        public  string   	SectionName               { get { return _Questionaires.SectionName; } set { _Questionaires.SectionName = value; } }
        
        /// <summary>
        /// Gets or sets the Options Property value.
        /// </summary>
        public QuestionOptions[] Options
        {
            get
            {
                QuestionOptions[] serv  = null;
                if (!string.IsNullOrEmpty(_Questionaires.Options))
                {
					MemoryStream ms = new MemoryStream(Encoding.ASCII.GetBytes(_Questionaires.Options));
    	            DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(QuestionOptions[]));
        	        serv = serializer.ReadObject(ms) as QuestionOptions[];
				}
                return serv;
								
            }
            set
            {
			 	if (value != null)
                {
                	 MemoryStream ms = new MemoryStream();
                	/// Serialize to JSON
                	DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(QuestionOptions[]));
                	serializer.WriteObject(ms, value);
                	ms.Position = 0;
                	using (StreamReader reader = new StreamReader(ms))
                  	 _Questionaires.Options = reader.ReadToEnd();
                	ms.Close();
				}
				 else
				   _Questionaires.Options = null;
            }
        }
        
        /// <summary>
        /// Gets or sets the Name Property value.
        /// </summary>
        public  string   	Name                      { get { return _Questionaires.Name; } set { _Questionaires.Name = value; } }
        
        /// <summary>
        /// Gets or sets the InputType Property value.
        /// </summary>
        public  QuestionType	InputType                 {get{ return (QuestionType)Enum.ToObject(typeof(QuestionType), _Questionaires.InputType); ;} set{ _Questionaires.InputType=(int) value;}}
        
        /// <summary>
        /// Gets or sets the IsAnswerReq Property value.
        /// </summary>
        public  bool     	IsAnswerReq               { get { return _Questionaires.IsAnswerReq; } set { _Questionaires.IsAnswerReq = value; } }
        

		
		public Questionaires InternalEntity 
		{ get
		  {
			return _Questionaires;
		  }
		}

    }    

 }

