//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization.Json;
using SS.Framework.Common;

namespace SS.DL.AzureTableStorage
{
    public class  User 
	
    {
    
		 Users _Users;
		
		public  User( Users Par)
        {
			_Users = Par;
        }
		public  User( )
        {
			_Users = new Users ();
        }
		
		public string RowKey  
		{
			get 
			{
				return _Users.RowKey;
			}
		}
        /// <summary>
        /// Gets or sets the UserPartithion Property value.
        /// </summary>
        public  string   	UserPartition             { get { return _Users.PartitionKey; } set { _Users.PartitionKey = value; } }
        /// <summary>
        /// Gets or sets the UserId Property value.
        /// </summary>
        public string UserId { get { return _Users.RowKey; } set { _Users.RowKey = SimpleHash.GenerateHashKey(value); } }

        /// <summary>
        /// Gets or sets the UserName Property value.
        /// </summary>
        public string UserName { get { return _Users.UserName; } set { _Users.UserName = value; } }

        /// <summary>
        /// Gets or sets the Password Property value.
        /// </summary>
        public string Password { get { return _Users.Password; } set { _Users.Password = SimpleHash.ComputeHash(value, "MD5", null); } }
        
        /// <summary>
        /// Gets or sets the IsAdmin Property value.
        /// </summary>
        public  bool     	IsAdmin                   { get { return _Users.IsAdmin; } set { _Users.IsAdmin = value; } }
        
        /// <summary>
        /// Gets or sets the Gender Property value.
        /// </summary>
        public  string   	Gender                    { get { return _Users.Gender; } set { _Users.Gender = value; } }
        
        /// <summary>
        /// Gets or sets the LastLoginDate Property value.
        /// </summary>
        public  string   	LastLoginDate             { get { return _Users.LastLoginDate; } set { _Users.LastLoginDate = value; } }
        
        /// <summary>
        /// Gets or sets the IsActive Property value.
        /// </summary>
        public  bool     	IsActive                  { get { return _Users.IsActive; } set { _Users.IsActive = value; } }
        
        /// <summary>
        /// Gets or sets the Latitude Property value.
        /// </summary>
        public  double   	Latitude                  { get { return _Users.Latitude; } set { _Users.Latitude = value; } }
        
        /// <summary>
        /// Gets or sets the Longitude Property value.
        /// </summary>
        public  double   	Longitude                 { get { return _Users.Longitude; } set { _Users.Longitude = value; } }
        
        /// <summary>
        /// Gets or sets the ChatId Property value.
        /// </summary>
        public  string   	ChatId                    { get { return _Users.ChatId; } set { _Users.ChatId = value; } }
        
        /// <summary>
        /// Gets or sets the CompatIndex Property value.
        /// </summary>
        public  int      	CompatIndex               { get { return _Users.CompatIndex; } set { _Users.CompatIndex = value; } }
        
        /// <summary>
        /// Gets or sets the DeviceName Property value.
        /// </summary>
        public  string   	DeviceName                { get { return _Users.DeviceName; } set { _Users.DeviceName = value; } }
        
        /// <summary>
        /// Gets or sets the DeviceVersion Property value.
        /// </summary>
        public  string   	DeviceVersion             { get { return _Users.DeviceVersion; } set { _Users.DeviceVersion = value; } }
        
        /// <summary>
        /// Gets or sets the DevicePlatform Property value.
        /// </summary>
        public  string   	DevicePlatform            { get { return _Users.DevicePlatform; } set { _Users.DevicePlatform = value; } }
        
        /// <summary>
        /// Gets or sets the DeviceId Property value.
        /// </summary>
        public  string   	DeviceId                  { get { return _Users.DeviceId; } set { _Users.DeviceId = value; } }
        
        /// <summary>
        /// Gets or sets the DevicePhGapVersion Property value.
        /// </summary>
        public  string   	DevicePhGapVersion        { get { return _Users.DevicePhGapVersion; } set { _Users.DevicePhGapVersion = value; } }
        
        /// <summary>
        /// Gets or sets the IsOnline Property value.
        /// </summary>
        public  bool     	IsOnline                  { get { return _Users.IsOnline; } set { _Users.IsOnline = value; } }
        
        /// <summary>
        /// Gets or sets the FacebookId Property value.
        /// </summary>
        public  string   	FacebookId                { get { return _Users.FacebookId; } set { _Users.FacebookId = value; } }
        
        /// <summary>
        /// Gets or sets the AppState Property value.
        /// </summary>
        public  AppStateType	AppState                  {get{ return (AppStateType)Enum.ToObject(typeof(AppStateType), _Users.AppState); ;} set{ _Users.AppState=(int) value;}}


        /// <summary>
        /// Gets or sets the AgeCheck Property value.
        /// </summary>
        public bool AgeCheck { get { return _Users.IsOnline; } set { _Users.IsOnline = value; } }

        /// <summary>
        /// Gets or sets the TCCheck Property value.
        /// </summary>
        public bool TCCheck { get { return _Users.IsOnline; } set { _Users.IsOnline = value; } }



        /// <summary>
        /// Gets or sets the FacebookId Property value.
        /// </summary>
        public string FirstName { get { return _Users.FirstName; } set { _Users.FirstName = value; } }

        /// <summary>
        /// Gets or sets the FacebookId Property value.
        /// </summary>
        public string LastName { get { return _Users.LastName; } set { _Users.LastName = value; } }

        /// <summary>
        /// Gets or sets the FacebookId Property value.
        /// </summary>
        public string Locale { get { return _Users.Locale; } set { _Users.Locale = value; } }



        /// <summary>
        /// Gets or sets the Score Property value.
        /// </summary>
        public CategoryScore[] Score
        {
            get
            {
                CategoryScore[] serv  = null;
                if (!string.IsNullOrEmpty(_Users.Score))
                {
					MemoryStream ms = new MemoryStream(Encoding.ASCII.GetBytes(_Users.Score));
    	            DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(CategoryScore[]));
        	        serv = serializer.ReadObject(ms) as CategoryScore[];
				}
                return serv;
								
            }
            set
            {
			 	if (value != null)
                {
                	 MemoryStream ms = new MemoryStream();
                	/// Serialize to JSON
                	DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(CategoryScore[]));
                	serializer.WriteObject(ms, value);
                	ms.Position = 0;
                	using (StreamReader reader = new StreamReader(ms))
                  	 _Users.Score = reader.ReadToEnd();
                	ms.Close();
				}
				 else
				   _Users.Score = null;
            }
        }
        

		
		public Users InternalEntity 
		{ get
		  {
			return _Users;
		  }
		}

    }    

 }
