//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;

namespace SS.DL.AzureTableStorage
{
    public class  UserDevices : TableServiceEntity
    {
        
		public  UserDevices()
        {

        }
		
	 	
        
        
        /// <summary>
        /// Gets or sets the DeviceName Property value.
        /// </summary>
        public  string   	DeviceName                {get; set;}
        
        /// <summary>
        /// Gets or sets the DeviceVersion Property value.
        /// </summary>
        public  string   	DeviceVersion             {get; set;}
        
        /// <summary>
        /// Gets or sets the DevicePlatform Property value.
        /// </summary>
        public  string   	DevicePlatform            {get; set;}
        
        /// <summary>
        /// Gets or sets the DevicePhGapVersion Property value.
        /// </summary>
        public  string   	DevicePhGapVersion        {get; set;}
        
	
	


    }    

 }
