//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization.Json;
using SS.Framework.Common;

namespace SS.DL.AzureTableStorage
{
    public class  UserQuestion 
	
    {
    
		 UserQuestions _UserQuestions;
		
		public  UserQuestion( UserQuestions Par)
        {
			_UserQuestions = Par;
        }
		public  UserQuestion( )
        {
			_UserQuestions = new UserQuestions ();
        }
		
		public string RowKey  
		{
			get 
			{
				return _UserQuestions.RowKey;
			}
		}
        /// <summary>
        /// Gets or sets the UserId Property value.
        /// </summary>
        public  string   	UserId                    { get { return _UserQuestions.PartitionKey; } set { _UserQuestions.PartitionKey = value; } }
        
        /// <summary>
        /// Gets or sets the QuestionId Property value.
        /// </summary>
        public  string   	QuestionId                { get { return _UserQuestions.RowKey; } set { _UserQuestions.RowKey = value; } }
        
        /// <summary>
        /// Gets or sets the CategoryId Property value.
        /// </summary>
        public  string   	CategoryId                { get { return _UserQuestions.CategoryId; } set { _UserQuestions.CategoryId = value; } }
        
        /// <summary>
        /// Gets or sets the Answer Property value.
        /// </summary>
        public  int      	Answer                    { get { return _UserQuestions.Answer; } set { _UserQuestions.Answer = value; } }
        
        /// <summary>
        /// Gets or sets the IsActive Property value.
        /// </summary>
        public  bool     	IsActive                  { get { return _UserQuestions.IsActive; } set { _UserQuestions.IsActive = value; } }
        

		
		public UserQuestions InternalEntity 
		{ get
		  {
			return _UserQuestions;
		  }
		}

    }    

 }
