//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization.Json;
using SS.Framework.Common;

namespace SS.DL.AzureTableStorage
{
    public class  UserLocation 
	
    {
    
		 UserLocations _UserLocations;
		
		public  UserLocation( UserLocations Par)
        {
			_UserLocations = Par;
        }
		public  UserLocation( )
        {
			_UserLocations = new UserLocations ();
        }
		
		public string RowKey  
		{
			get 
			{
				return _UserLocations.RowKey;
			}
		}
        /// <summary>
        /// Gets or sets the Latitude Property value.
        /// </summary>
        public  string   	Latitude                  { get { return _UserLocations.PartitionKey; } set { _UserLocations.PartitionKey = value; } }
        
        /// <summary>
        /// Gets or sets the Longitude Property value.
        /// </summary>
        public  string   	Longitude                 { get { return _UserLocations.RowKey; } set { _UserLocations.RowKey = value; } }
        
        /// <summary>
        /// Gets or sets the UserId Property value.
        /// </summary>
        public  string   	UserId                    { get { return _UserLocations.UserId; } set { _UserLocations.UserId = value; } }
        
        /// <summary>
        /// Gets or sets the LocationTime Property value.
        /// </summary>
        public  DateTime 	LocationTime              { get { return _UserLocations.LocationTime; } set { _UserLocations.LocationTime = value; } }
        

		
		public UserLocations InternalEntity 
		{ get
		  {
			return _UserLocations;
		  }
		}

    }    

 }
