//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization.Json;
using SS.Framework.Common;

namespace SS.DL.AzureTableStorage
{
    public class  User 
	
    {
    
		 Users _Users;
		
		public  User( Users Par)
        {
			_Users = Par;
        }
		public  User( )
        {
			_Users = new Users ();
        }
		
		public string RowKey  
		{
			get 
			{
				return _Users.RowKey;
			}
		}
        /// <summary>
        /// Gets or sets the UserPartition Property value.
        /// </summary>
        public  string   	UserPartition             { get { return _Users.PartitionKey; } set { _Users.PartitionKey = value; } }

        /// <summary>
        /// Gets or sets the UserId Property value.
        /// </summary>
        public  string   	UserId                    { get { return _Users.RowKey; } set { _Users.RowKey = SimpleHash.GenerateHashKey(value); } }
        
        /// <summary>
        /// Gets or sets the UserName Property value.
        /// </summary>
        public  string   	UserName                  { get { return _Users.UserName; } set { _Users.UserName = value; } }
        
        /// <summary>
        /// Gets or sets the Password Property value.
        /// </summary>
        public  string   	Password                  { get { return _Users.Password; } set { _Users.Password = SimpleHash.ComputeHash(value,"MD5" ,null); } }
        
        /// <summary>
        /// Gets or sets the IsAdmin Property value.
        /// </summary>
        public  bool     	IsAdmin                   { get { return _Users.IsAdmin; } set { _Users.IsAdmin = value; } }
        
        /// <summary>
        /// Gets or sets the Gender Property value.
        /// </summary>
        public  string   	Gender                    { get { return _Users.Gender; } set { _Users.Gender = value; } }
        
        /// <summary>
        /// Gets or sets the LastLoginDate Property value.
        /// </summary>
        public  string   	LastLoginDate             { get { return _Users.LastLoginDate; } set { _Users.LastLoginDate = value; } }
        
        /// <summary>
        /// Gets or sets the IsActive Property value.
        /// </summary>
        public  bool     	IsActive                  { get { return _Users.IsActive; } set { _Users.IsActive = value; } }
        
        /// <summary>
        /// Gets or sets the Latitude Property value.
        /// </summary>
        public  double   	Latitude                  { get { return _Users.Latitude; } set { _Users.Latitude = value; } }
        
        /// <summary>
        /// Gets or sets the Longitude Property value.
        /// </summary>
        public  double   	Longitude                 { get { return _Users.Longitude; } set { _Users.Longitude = value; } }
        
        /// <summary>
        /// Gets or sets the ChatId Property value.
        /// </summary>
        public  string   	ChatId                    { get { return _Users.ChatId; } set { _Users.ChatId = value; } }
        
        /// <summary>
        /// Gets or sets the Score Property value.
        /// </summary>
        public  int      	Score                     { get { return _Users.Score; } set { _Users.Score = value; } }
        
        /// <summary>
        /// Gets or sets the CompatIndex Property value.
        /// </summary>
        public  int      	CompatIndex               { get { return _Users.CompatIndex; } set { _Users.CompatIndex = value; } }
        

		
		public Users InternalEntity 
		{ get
		  {
			return _Users;
		  }
		}

    }    

 }

