//------------------------------------------------------------------------------
// <autogenerated>
//    This code was generated by a CodeSmith Template.
//
//    This is for customizing generated code
//    All changes made in this file will be preserved.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Data.Services.Client;

namespace SS.DL.AzureTableStorage
{
    public partial class UserQuestionContext
    {
        /* 
	
        //   This is an example of custom developed query
        public List<UserQuestion> MethodName(list of method parameters )
            {
                List<UserQuestion> rez = new List<UserQuestion>();
                NextRecordInfo nextRec = new NextRecordInfo() ;
                    do	
                    {
                        DataServiceQuery<UserQuestions> Qtran = (DataServiceQuery<UserQuestions>)servCtx.CreateQuery<UserQuestions>(TableName).Where(c => enter query details here );
                        nextRec = GetNextPage(ref rez, Qtran, nextRec, 0);
                    }
                    while (!string.IsNullOrEmpty(nextRec.NextPartition));        
                return rez;
            }
	
        */

        //Add your extension methods here for  UserQuestionContext class.


    }

 }

