//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization.Json;
using WPS.DL.Entity;
using WPS.Framework.Common;

namespace WPS.DL.AzureTableStorage
{
    public class  DisabledCustomer 
	
    {
    
		 DisabledCustomers _DisabledCustomers;
		
		public  DisabledCustomer( DisabledCustomers Par)
        {
			_DisabledCustomers = Par;
        }
		public  DisabledCustomer( )
        {
			_DisabledCustomers = new DisabledCustomers ();
        }
		
		public string RowKey  
		{
			get 
			{
				return _DisabledCustomers.RowKey;
			}
		}
        /// <summary>
        /// Gets or sets the CustomerId Property value.
        /// </summary>
        public  string   	CustomerId                { get { return _DisabledCustomers.PartitionKey; } set { _DisabledCustomers.PartitionKey = value; } }
        
        /// <summary>
        /// Gets or sets the UserId Property value.
        /// </summary>
        public  string   	UserId                    { get { return _DisabledCustomers.RowKey; } set { _DisabledCustomers.RowKey = value; } }
        
        /// <summary>
        /// Gets or sets the TrustedCustomer Property value.
        /// </summary>
        public  bool     	TrustedCustomer           { get { return _DisabledCustomers.TrustedCustomer; } set { _DisabledCustomers.TrustedCustomer = value; } }
        

		
		public DisabledCustomers InternalEntity 
		{ get
		  {
			return _DisabledCustomers;
		  }
		}

    }    

 }

