//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;

namespace WPS.DL.AzureTableStorage
{
    public class  DisabledCustomers : TableServiceEntity
    {
        
		public  DisabledCustomers()
        {

        }
		
	 	
        
        
        /// <summary>
        /// Gets or sets the TrustedCustomer Property value.
        /// </summary>
        public  bool     	TrustedCustomer           {get; set;}
        
	
	


    }    

 }

