//------------------------------------------------------------------------------
// <autogenerated>
//    This code was generated by a CodeSmith Template.
//
//    This is for customizing generated code
//    All changes made in this file will be preserved.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Data.Services.Client;

namespace WPS.DL.AzureTableStorage
{
    public partial class DisabledCustomerContext
    {
        /* 
	
        //   This is an example of custom developed query
        public List<DisabledCustomer> MethodName(list of method parameters )
            {
                List<DisabledCustomer> rez = new List<DisabledCustomer>();
                NextRecordInfo nextRec = new NextRecordInfo() ;
                    do	
                    {
                        DataServiceQuery<DisabledCustomers> Qtran = (DataServiceQuery<DisabledCustomers>)servCtx.CreateQuery<DisabledCustomers>(TableName).Where(c => enter query details here );
                        nextRec = GetNextPage(ref rez, Qtran, nextRec, 0);
                    }
                    while (!string.IsNullOrEmpty(nextRec.NextPartition));        
                return rez;
            }
	
        */

        //Add your extension methods here for  DisabledCustomerContext class.

        public bool IsCustomerEnabled(string custId)
        {
            DisabledCustomer dist = GetById(custId, custId);
            if (dist != null)
                return dist.TrustedCustomer;
            else
                return true;
        }



    }
}
