//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization.Json;
using SS.Framework.Common;

namespace SS.DL.AzureTableStorage
{
    public class  ErrorMapping 
	
    {
    
		 ErrorMappings _ErrorMappings;
		
		public  ErrorMapping( ErrorMappings Par)
        {
			_ErrorMappings = Par;
        }
		public  ErrorMapping( )
        {
			_ErrorMappings = new ErrorMappings ();
        }
		
		public string RowKey  
		{
			get 
			{
				return _ErrorMappings.RowKey;
			}
		}
        /// <summary>
        /// Gets or sets the ErrorCode Property value.
        /// </summary>
        public  string   	ErrorCode                 { get { return _ErrorMappings.RowKey; } set { _ErrorMappings.RowKey = value; } }
        
        /// <summary>
        /// Gets or sets the Subsystem Property value.
        /// </summary>
        public  string   	Subsystem                 { get { return _ErrorMappings.PartitionKey; } set { _ErrorMappings.PartitionKey = value; } }
        
        /// <summary>
        /// Gets or sets the ErrorMessage Property value.
        /// </summary>
        public  string   	ErrorMessage              { get { return _ErrorMappings.ErrorMessage; } set { _ErrorMappings.ErrorMessage = value; } }
        
        /// <summary>
        /// Gets or sets the UserError Property value.
        /// </summary>
        public  bool     	UserError                 { get { return _ErrorMappings.UserError; } set { _ErrorMappings.UserError = value; } }
        

		
		public ErrorMappings InternalEntity 
		{ get
		  {
			return _ErrorMappings;
		  }
		}

    }    

 }

