//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.WindowsAzure.StorageClient;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization.Json;
using SS.Framework.Common;

namespace SS.DL.AzureTableStorage
{
    public class  UserChat 
	
    {
    
		 UserChats _UserChats;
		
		public  UserChat( UserChats Par)
        {
			_UserChats = Par;
        }
		public  UserChat( )
        {
			_UserChats = new UserChats ();
        }
		
		public string RowKey  
		{
			get 
			{
				return _UserChats.RowKey;
			}
		}
        /// <summary>
        /// Gets or sets the UserId Property value.
        /// </summary>
        public  string   	UserId                    { get { return _UserChats.PartitionKey; } set { _UserChats.PartitionKey = value; } }
        
        /// <summary>
        /// Gets or sets the ChatId Property value.
        /// </summary>
        public  string   	ChatId                    { get { return _UserChats.RowKey; } set { _UserChats.RowKey = value; } }
        
        /// <summary>
        /// Gets or sets the ChatTime Property value.
        /// </summary>
        public  DateTime 	ChatTime                  { get { return _UserChats.ChatTime; } set { _UserChats.ChatTime = value; } }
        

		
		public UserChats InternalEntity 
		{ get
		  {
			return _UserChats;
		  }
		}

    }    

 }

